services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      TZ: "UTC"
    volumes:
      - ./src/public/ahorcado:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
